package com.example.todos.models;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.example.todos.constants.ApplicationConstants;
import com.fasterxml.jackson.annotation.JsonInclude;
import lombok.*;

@Setter
@Getter
@DynamoDBTable(tableName = ApplicationConstants.TODOS_TABLE)
public class Todo {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute
    private String title;
    @DynamoDBAttribute
    private Boolean completed;
}
